import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbarLogin";
import AwwwardsTheme from "@/components/awardstheme";
import { ThemeProvider } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={AwwwardsTheme}>
          <Navbar>{children}</Navbar>
        </ThemeProvider>
      </body>
    </html>
  );
}
