import "./globals.css";
import dynamic from "next/dynamic";

import { Inter } from "next/font/google";
import AwwwardsTheme from "@/components/awardstheme";
import { ThemeProvider } from "@mui/material";
const Navbar = dynamic(() => import("@/components/navbarLogin"), {
  ssr: false,
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={AwwwardsTheme}>
          <Navbar>{children}</Navbar>
        </ThemeProvider>
      </body>
    </html>
  );
}
